### ISSUE TITLE
Review: JS Advanced. Prototype & OOP

### ISSUE THREAD

**Issue by AlekseiIvshin** [RuisuLee/EPAMExternalFELab2017#2]
Task1 - 1
Task2 - 0 -  Надо следовать контракту при переопределении методов (toString & valueOf)

Task3 - 0 Наследование предполагает, что проверка instanceof со всеми родительскими классами будет возвращать true. Например, `new MonsterTruck() instanceof Vehical -> true`
Task4 - 2

**Итоговая оценка 0**

**Comment by RuisuLee** [comment]
1. Исправила переопределение методов toString и valueOf в задании 
2. Доработала наследование в задании 3

**Comment by AlekseiIvshin** [comment]
Отлично!
Task1 - 1
Task2 - 1
Task3 - 1
Task4 - 2

**Итоговая оценка 2**
